#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

# Description: Remove initrd line from GRUBv1 and GRUBv2 config files.

REQUIRE_CANTBOOT_VERSION_MAGIC 1

sed -i '/^\s*initrd/d' ${possible_grub_cfgfile_locations} &>/dev/null

REBOOT