#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

# Description: Put typo in selinux/config to cause missing policy kernel panic.

REQUIRE_CANTBOOT_VERSION_MAGIC 1
REQUIRE_SELINUX_CFGFILE

cat >/etc/selinux/config <<EOF
SELINUX=enforcing
SELINUXTYPE=permissive
EOF

REBOOT