#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

# Rname a swap LV

REQUIRE_LVM_SWAP

swapoff ${swapdev}
lvrename ${LVM2_VG_NAME}/${LVM2_LV_NAME} ${LVM2_VG_NAME}/${LVM2_LV_NAME}1 >/dev/null

sed -i "s,${LVM2_VG_NAME}.${LVM2_LV_NAME},&11," /etc/fstab
[[ -n ${UUID} ]] && sed -i "s,${UUID},${UUID::30}1d9a," /etc/fstab
[[ -n ${LABEL} ]] && sed -i "s,LABEL=${LABEL},LABEL=${LABEL}1," /etc/fstab

#REBOOT