#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

# Description: Rename GRUB v1 or v2 config files to <FILE>.old allowing for quick recovery.

REQUIRE_CANTBOOT_VERSION_MAGIC 1

nothing_renamed=True

for file in ${possible_grub_cfgfile_locations}; do
    mv ${file} ${file}.old 2>/dev/null && nothing_renamed=False
done

if [[ ${nothing_renamed} == True ]]; then
    sorryText="requires some version of GRUB but couldn't find any GRUB configs in /boot"
    SORRY
fi

REBOOT