#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

# Destroy GRUBv1 stage 2 img file on bootfs

REQUIRE_CANTBOOT_VERSION_MAGIC 1
REQUIRE_GRUB1

shred --remove --zero /boot/grub/stage2

REBOOT