#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

# Remove initrd line from GRUB config file

sed -i '/^\s*initrd/d' ${possible_grub_cfgfile_locations} &>/dev/null

REBOOT