#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

cd breaks
echo * | column -t | fold -sw80 >../tokenlist