#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

cd breaks
echo * | fold -sw60 | column -t >../tokens-ls
for f in *; do
    printf "▪ ${f} :"
    if grep -q '^# Description:' "${f}"; then
        grep '^# Description:' "${f}" | cut -d: -f2-
    else
        echo
    fi
done >../tokens-ll