#!/bin/bash
# This file is part of cantboot <https://github.com/ryran/cantboot>
# Copyright Ryan Sawhill Aroha <rsaw@redhat.com> & cantboot contributors
# License: GPL v3

cd breaks
echo * | fold -sw60 | column -t >../token-ls
for f in *; do
    grep -q '^# Description:' "${f}" &&
        printf "▪ "
        grep -H '^# Description:' "${f}" | cut -d: -f1,3-
done >../token-ll